version: "3.9"
services:
  collector:
    build: .
    volumes:
      - ./src:/src
      - ./images:/images
    # working_dir: /src
    # command: flask run
    environment:
      DIR_NAME: /images
      OPENCV_FFMPEG_CAPTURE_OPTIONS: rtsp_transport;tcp
    #   STREAM_URL:  ${STREAM_URL}
    #   FLASK_ENV: ${FLASK_ENV}
    #   FLASK_APP: ${FLASK_APP}
    #   FLASK_RUN_HOST: ${FLASK_RUN_HOST}
    #   RECORD_FROM: ${RECORD_FROM}
    #   RECORD_TO: ${RECORD_TO}
    #   SCALE: ${SCALE}
    #   CAPTURE_INTERVAL: ${CAPTURE_INTERVAL}
    restart: always
    # network_mode: "host" 
    # ports:
    #   - "5000:5000"